/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.berrel;

import javax.swing.JOptionPane;

/**
 *
 * @author corte
 */
public class average extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(average.class.getName());

    /**
     * Creates new form average
     */
    public average() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt3rd = new javax.swing.JTextField();
        txt4th = new javax.swing.JTextField();
        txt2nd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt1st = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt3rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 147, 154, 41));
        getContentPane().add(txt4th, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 194, 154, 41));
        getContentPane().add(txt2nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 100, 154, 41));

        jLabel1.setText("1st Quarter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 65, 98, -1));

        jLabel2.setText("2nd Quarter");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 112, 98, -1));

        jLabel3.setText("3rd Quarter");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 159, 98, -1));

        jLabel4.setText("4th Quarter");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 206, 98, -1));

        jButton1.setText("AVERAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 253, 105, 38));
        getContentPane().add(txt1st, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 53, 154, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int grade1 = Integer.parseInt(txt1st.getText());
        int grade2 = Integer.parseInt(txt2nd.getText());
        int grade3 = Integer.parseInt(txt3rd.getText());
        int grade4 = Integer.parseInt(txt4th.getText());

        int sum = grade1 + grade2 + grade3 + grade4;
        int ave = sum/4;

        JOptionPane.showMessageDialog(null, "Average: " +ave, "Average", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new average().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt1st;
    private javax.swing.JTextField txt2nd;
    private javax.swing.JTextField txt3rd;
    private javax.swing.JTextField txt4th;
    // End of variables declaration//GEN-END:variables
}
